language: node_js
node_js:
  - "8"
dist: trusty # needs Ubuntu Trusty
# Note: if you switch to sudo: false, you'll need to launch Chrome with --no-sandbox.
# See https://github.com/travis-ci/travis-ci/issues/8836
sudo: required
addons:
  chrome: stable # have Travis install Chrome stable.
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
before_script:
  - chmod +x ./scripts/cc-test-reporter
  - ./scripts/cc-test-reporter before-build
script:
  - yarn test --watch=false --code-coverage
after_success:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
  - ./scripts/cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - rm -rf ./coverage
before_deploy:
  - yarn run build -- --base-href=https://lgcolella.github.io/Quizzer/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master